# Generated by Django 5.2.12 on 2026-04-03 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('login', 'Mot de passe'), ('card', 'Carte bancaire'), ('note', 'Note sécurisée')], default='login', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('favorite', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('password', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('card_holder', models.CharField(blank=True, default='', max_length=200)),
                ('card_number', models.CharField(blank=True, default='', max_length=50)),
                ('expiry', models.CharField(blank=True, default='', max_length=10)),
                ('cvv', models.CharField(blank=True, default='', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée du coffre',
                'verbose_name_plural': 'Entrées du coffre',
                'ordering': ['-created_at'],
            },
        ),
    ]
